version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
    commands:
      - echo "Installing dependencies..."
      - rbenv install 3.2.0 && rbenv global 3.2.0
      - gem install bundler
      - bundle install

      # # Install nvm
      # - echo "Installing NVM..."
      # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
      # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

      # # Install Node.js using nvm
      # - echo "Installing Node JS..."
      # - nvm install 14
      # - nvm use 14

      # Install yarn
      - echo "Installing yarn..."
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt update
      - sudo apt install yarn
      - yarn install

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # Add any additional pre-build tasks specific to your application, such as database setup or environment configuration.

  build:
    commands:
      - echo "Running build tasks..."
      - rails db:migrate
      # - bundle exec rake assets:precompile
      # Add any additional build tasks specific to your application, such as running tests or generating documentation.

  post_build:
    commands:
      - echo "Running post-build tasks..."
      # Add any additional post-build tasks specific to your application, such as cleaning up temporary files or generating artifacts.

artifacts:
  files:
    - '**/*'
  name: rails_messageme
